
'use client';

import { Card, CardContent } from '@/components/ui/card';
import { Rocket, HandCoins, Users, Briefcase, TrendingUp, CalendarDays } from 'lucide-react';
import CountUp from 'react-countup';

const stats = [
  {
    icon: <Rocket className="h-8 w-8 text-primary" />,
    value: 230,
    suffix: '+',
    label: 'Startups Incubated',
  },
  {
    icon: <HandCoins className="h-8 w-8 text-primary" />,
    value: 10,
    suffix: ' Cr+',
    label: 'Funds to support Startup',
  },
  {
    icon: <Users className="h-8 w-8 text-primary" />,
    value: 50000,
    suffix: '+',
    label: 'Students Reached',
  },
  {
    icon: <Briefcase className="h-8 w-8 text-primary" />,
    value: 1390,
    suffix: '+',
    label: 'Employment Generated',
  },
  {
    icon: <TrendingUp className="h-8 w-8 text-primary" />,
    value: 30,
    suffix: 'Cr+',
    label: 'Revenue generated by Startups',
  },
  {
    icon: <CalendarDays className="h-8 w-8 text-primary" />,
    value: 100,
    suffix: '+',
    label: 'Annual Networking Events',
  },
];

export default function Stats() {
  return (
    <section className="py-16 md:py-24 bg-card">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center max-w-2xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold">Our Impact in Numbers</h2>
          <p className="mt-4 text-muted-foreground">
            We are proud of the community we've built and the success of our startups.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-6">
          {stats.map((stat, index) => (
            <Card key={index} className="text-center p-4 bg-background border transition-transform hover:-translate-y-2 hover:shadow-lg">
              <CardContent className="p-2 flex flex-col items-center justify-center gap-2">
                {stat.icon}
                <div className="text-3xl md:text-4xl font-bold text-primary">
                  <CountUp end={stat.value} duration={3} separator="," />{stat.suffix}
                </div>
                <p className="text-sm text-muted-foreground">{stat.label}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
